---

- name: Install fwknop server
  package: name=fwknop-server state=latest

- name: Copy fwknopd.conf
  template:
    src: fwknopd.conf.j2
    dest: /etc/fwknop/fwknopd.conf
  notify: Restart fwknop server

- name: Copy /etc/default
  copy:
    src: etc_default_fwknop-server
    dest: /etc/default/fwknop-server
  notify: Restart fwknop server

- name: Copy access.conf
  template:
    src: access.conf.j2
    dest: /etc/fwknop/access.conf
  notify: Restart fwknop server
